name: berlingo
description: Language learning app with 8 levels - Learn English, Chinese, Korean and more!
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_linter: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/languages.json
    - assets/lessons.json
